name: CI
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
    - run: |
        cd /path/to/project
        npm cache clean --force
  build:
    needs: setup
    runs-on: ubuntu-18.04
    steps:
    - run: |
        ls
        npm install
        npm run build 
  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:  
    - run: |
        rm -rf public
        mkdir public && cp -rf dist/* public
