name:CI
on:
  push:
    branchs:
      - main
jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      run: 
        npm install
        npm run build 
  deploy:
    steps:  
      run: 
        rm -rf public
        mkdir public && cp -rf dist/* public
