name: CI
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@main
    - run: |
        npm cache clean --force
        ls
  build:
    needs: setup
    runs-on: ubuntu-18.04
    steps:
    - run: |
        npm install
        npm run build 
  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:  
    - run: |
        rm -rf public
        mkdir public && cp -rf dist/* public
