name:CI

on:
  push:
    branch:
      - main
env:
  node:latest


jobs:
  build:
    steps:
      run: 
        npm install
        npm run build 
  deploy:
    steps:  
      run: 
        rm -rf public
        mkdir public && cp -rf dist/* public


cache:
  paths:
    - node_modules
    - dist
