name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: |
        npm cache clean --force
        npm install
        npm run build 
        ls
        rm -rf public
        mkdir public && cp -rf dist/* public
