name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - run: 
        npm install
        npm run build 
  deploy:
    runs-on: ubuntu-18.04
    steps:  
    - run: 
        rm -rf public
        mkdir public && cp -rf dist/* public
