name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: setup
      run: |
        npm cache clean --force
    - name: build
      run: |
        npm install
        npm run build 
    - name: deploy
      run: |
        ls
        rm -rf public
        mkdir public && cp -rf dist/* public
